// Writes app/config.js from env vars so the browser knows which Supabase to use.
// Run: npm run config   (reads .env if it exists)
// On Vercel this runs as the build command.
// Missing values = empty strings = the app runs in DEMO MODE.
// Never put ANTHROPIC_API_KEY here: everything in app/ is public.
import { writeFileSync } from "node:fs";

const supabaseUrl = (process.env.SUPABASE_URL || "").trim();
const supabaseAnonKey = (process.env.SUPABASE_ANON_KEY || "").trim();

const out = `// GENERATED by scripts/make-config.mjs. Don't edit, don't commit.
window.PP_CONFIG = ${JSON.stringify({ supabaseUrl, supabaseAnonKey }, null, 2)};
`;
writeFileSync(new URL("../app/config.js", import.meta.url), out);

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn("make-config: SUPABASE_URL or SUPABASE_ANON_KEY is missing, so app/config.js is empty and the app will run in DEMO MODE.");
} else {
  console.log("make-config: wrote app/config.js (Supabase mode).");
}
